# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /root/Documents/code/c/clion-2016.3.4/bin/cmake/bin/cmake

# The command to remove a file.
RM = /root/Documents/code/c/clion-2016.3.4/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/Documents/code/c/BatailleNavale

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/Documents/code/c/BatailleNavale

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/root/Documents/code/c/clion-2016.3.4/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/root/Documents/code/c/clion-2016.3.4/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Documents/code/c/BatailleNavale/CMakeFiles /root/Documents/code/c/BatailleNavale/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Documents/code/c/BatailleNavale/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BN

# Build rule for target.
BN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BN
.PHONY : BN

# fast build rule for target.
BN/fast:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/build
.PHONY : BN/fast

src/Allegro.o: src/Allegro.cpp.o

.PHONY : src/Allegro.o

# target to build an object file
src/Allegro.cpp.o:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Allegro.cpp.o
.PHONY : src/Allegro.cpp.o

src/Allegro.i: src/Allegro.cpp.i

.PHONY : src/Allegro.i

# target to preprocess a source file
src/Allegro.cpp.i:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Allegro.cpp.i
.PHONY : src/Allegro.cpp.i

src/Allegro.s: src/Allegro.cpp.s

.PHONY : src/Allegro.s

# target to generate assembly for a file
src/Allegro.cpp.s:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Allegro.cpp.s
.PHONY : src/Allegro.cpp.s

src/Bateau.o: src/Bateau.cpp.o

.PHONY : src/Bateau.o

# target to build an object file
src/Bateau.cpp.o:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Bateau.cpp.o
.PHONY : src/Bateau.cpp.o

src/Bateau.i: src/Bateau.cpp.i

.PHONY : src/Bateau.i

# target to preprocess a source file
src/Bateau.cpp.i:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Bateau.cpp.i
.PHONY : src/Bateau.cpp.i

src/Bateau.s: src/Bateau.cpp.s

.PHONY : src/Bateau.s

# target to generate assembly for a file
src/Bateau.cpp.s:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Bateau.cpp.s
.PHONY : src/Bateau.cpp.s

src/Croiseur.o: src/Croiseur.cpp.o

.PHONY : src/Croiseur.o

# target to build an object file
src/Croiseur.cpp.o:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Croiseur.cpp.o
.PHONY : src/Croiseur.cpp.o

src/Croiseur.i: src/Croiseur.cpp.i

.PHONY : src/Croiseur.i

# target to preprocess a source file
src/Croiseur.cpp.i:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Croiseur.cpp.i
.PHONY : src/Croiseur.cpp.i

src/Croiseur.s: src/Croiseur.cpp.s

.PHONY : src/Croiseur.s

# target to generate assembly for a file
src/Croiseur.cpp.s:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Croiseur.cpp.s
.PHONY : src/Croiseur.cpp.s

src/Cuirasse.o: src/Cuirasse.cpp.o

.PHONY : src/Cuirasse.o

# target to build an object file
src/Cuirasse.cpp.o:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Cuirasse.cpp.o
.PHONY : src/Cuirasse.cpp.o

src/Cuirasse.i: src/Cuirasse.cpp.i

.PHONY : src/Cuirasse.i

# target to preprocess a source file
src/Cuirasse.cpp.i:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Cuirasse.cpp.i
.PHONY : src/Cuirasse.cpp.i

src/Cuirasse.s: src/Cuirasse.cpp.s

.PHONY : src/Cuirasse.s

# target to generate assembly for a file
src/Cuirasse.cpp.s:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Cuirasse.cpp.s
.PHONY : src/Cuirasse.cpp.s

src/Destroyer.o: src/Destroyer.cpp.o

.PHONY : src/Destroyer.o

# target to build an object file
src/Destroyer.cpp.o:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Destroyer.cpp.o
.PHONY : src/Destroyer.cpp.o

src/Destroyer.i: src/Destroyer.cpp.i

.PHONY : src/Destroyer.i

# target to preprocess a source file
src/Destroyer.cpp.i:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Destroyer.cpp.i
.PHONY : src/Destroyer.cpp.i

src/Destroyer.s: src/Destroyer.cpp.s

.PHONY : src/Destroyer.s

# target to generate assembly for a file
src/Destroyer.cpp.s:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Destroyer.cpp.s
.PHONY : src/Destroyer.cpp.s

src/Menu.o: src/Menu.cpp.o

.PHONY : src/Menu.o

# target to build an object file
src/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Menu.cpp.o
.PHONY : src/Menu.cpp.o

src/Menu.i: src/Menu.cpp.i

.PHONY : src/Menu.i

# target to preprocess a source file
src/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Menu.cpp.i
.PHONY : src/Menu.cpp.i

src/Menu.s: src/Menu.cpp.s

.PHONY : src/Menu.s

# target to generate assembly for a file
src/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Menu.cpp.s
.PHONY : src/Menu.cpp.s

src/Partie.o: src/Partie.cpp.o

.PHONY : src/Partie.o

# target to build an object file
src/Partie.cpp.o:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Partie.cpp.o
.PHONY : src/Partie.cpp.o

src/Partie.i: src/Partie.cpp.i

.PHONY : src/Partie.i

# target to preprocess a source file
src/Partie.cpp.i:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Partie.cpp.i
.PHONY : src/Partie.cpp.i

src/Partie.s: src/Partie.cpp.s

.PHONY : src/Partie.s

# target to generate assembly for a file
src/Partie.cpp.s:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Partie.cpp.s
.PHONY : src/Partie.cpp.s

src/Sousmarin.o: src/Sousmarin.cpp.o

.PHONY : src/Sousmarin.o

# target to build an object file
src/Sousmarin.cpp.o:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Sousmarin.cpp.o
.PHONY : src/Sousmarin.cpp.o

src/Sousmarin.i: src/Sousmarin.cpp.i

.PHONY : src/Sousmarin.i

# target to preprocess a source file
src/Sousmarin.cpp.i:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Sousmarin.cpp.i
.PHONY : src/Sousmarin.cpp.i

src/Sousmarin.s: src/Sousmarin.cpp.s

.PHONY : src/Sousmarin.s

# target to generate assembly for a file
src/Sousmarin.cpp.s:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Sousmarin.cpp.s
.PHONY : src/Sousmarin.cpp.s

src/Tire.o: src/Tire.cpp.o

.PHONY : src/Tire.o

# target to build an object file
src/Tire.cpp.o:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Tire.cpp.o
.PHONY : src/Tire.cpp.o

src/Tire.i: src/Tire.cpp.i

.PHONY : src/Tire.i

# target to preprocess a source file
src/Tire.cpp.i:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Tire.cpp.i
.PHONY : src/Tire.cpp.i

src/Tire.s: src/Tire.cpp.s

.PHONY : src/Tire.s

# target to generate assembly for a file
src/Tire.cpp.s:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/Tire.cpp.s
.PHONY : src/Tire.cpp.s

src/crossplatform.o: src/crossplatform.cpp.o

.PHONY : src/crossplatform.o

# target to build an object file
src/crossplatform.cpp.o:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/crossplatform.cpp.o
.PHONY : src/crossplatform.cpp.o

src/crossplatform.i: src/crossplatform.cpp.i

.PHONY : src/crossplatform.i

# target to preprocess a source file
src/crossplatform.cpp.i:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/crossplatform.cpp.i
.PHONY : src/crossplatform.cpp.i

src/crossplatform.s: src/crossplatform.cpp.s

.PHONY : src/crossplatform.s

# target to generate assembly for a file
src/crossplatform.cpp.s:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/crossplatform.cpp.s
.PHONY : src/crossplatform.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/myhelper.o: src/myhelper.cpp.o

.PHONY : src/myhelper.o

# target to build an object file
src/myhelper.cpp.o:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/myhelper.cpp.o
.PHONY : src/myhelper.cpp.o

src/myhelper.i: src/myhelper.cpp.i

.PHONY : src/myhelper.i

# target to preprocess a source file
src/myhelper.cpp.i:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/myhelper.cpp.i
.PHONY : src/myhelper.cpp.i

src/myhelper.s: src/myhelper.cpp.s

.PHONY : src/myhelper.s

# target to generate assembly for a file
src/myhelper.cpp.s:
	$(MAKE) -f CMakeFiles/BN.dir/build.make CMakeFiles/BN.dir/src/myhelper.cpp.s
.PHONY : src/myhelper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BN"
	@echo "... src/Allegro.o"
	@echo "... src/Allegro.i"
	@echo "... src/Allegro.s"
	@echo "... src/Bateau.o"
	@echo "... src/Bateau.i"
	@echo "... src/Bateau.s"
	@echo "... src/Croiseur.o"
	@echo "... src/Croiseur.i"
	@echo "... src/Croiseur.s"
	@echo "... src/Cuirasse.o"
	@echo "... src/Cuirasse.i"
	@echo "... src/Cuirasse.s"
	@echo "... src/Destroyer.o"
	@echo "... src/Destroyer.i"
	@echo "... src/Destroyer.s"
	@echo "... src/Menu.o"
	@echo "... src/Menu.i"
	@echo "... src/Menu.s"
	@echo "... src/Partie.o"
	@echo "... src/Partie.i"
	@echo "... src/Partie.s"
	@echo "... src/Sousmarin.o"
	@echo "... src/Sousmarin.i"
	@echo "... src/Sousmarin.s"
	@echo "... src/Tire.o"
	@echo "... src/Tire.i"
	@echo "... src/Tire.s"
	@echo "... src/crossplatform.o"
	@echo "... src/crossplatform.i"
	@echo "... src/crossplatform.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/myhelper.o"
	@echo "... src/myhelper.i"
	@echo "... src/myhelper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

